<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: superadmin
 * Date: Wed, 05 Aug 2020 01:56:04 +0300
 */

$conf['title'] = 'Free TON Wiki';
$conf['lang'] = 'ru';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'gnufdl';
$conf['savedir'] = '********************';			// The real value is hidden for security reasons
$conf['baseurl'] = 'https://freeton.wiki';
$conf['breadcrumbs'] = 7;
$conf['youarehere'] = 1;
$conf['deaccent'] = '2';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'rss';
$conf['auth_security_timeout'] = 0;					// The real value is hidden for security reasons
$conf['target']['extern'] = '_blank';
$conf['jpg_quality'] = 80;
$conf['registernotify'] = '********************';	// The real value is hidden for security reasons
$conf['mailfrom'] = 'no-reply@freeton.wiki';
$conf['sitemap'] = 3;
$conf['userewrite'] = '1';
$conf['sepchar'] = '-';
$conf['defer_js'] = 0;
$conf['dnslookups'] = 0;
$conf['jquerycdn'] = 'cdnjs';
$conf['plugin']['smtp']['smtp_host'] = 'mail.freeton.wiki';
$conf['plugin']['smtp']['auth_user'] = 'no-reply@freeton.wiki';
$conf['plugin']['smtp']['auth_pass'] = '********************';		// The real value is hidden for security reasons
$conf['plugin']['smtp']['localdomain'] = 'freeton.wiki';
$conf['plugin']['translation']['translations'] = 'en ru ko';
$conf['plugin']['translation']['display'] = 'flag';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['translation']['copytrans'] = 1;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cerulean';
$conf['tpl']['bootstrap3']['themeByNamespace'] = 1;
$conf['tpl']['bootstrap3']['showTranslation'] = 1;
$conf['tpl']['bootstrap3']['showEditBtn'] = 'always';
$conf['tpl']['bootstrap3']['showAdminMenu'] = 1;
$conf['tpl']['bootstrap3']['notifyExtensionsUpdate'] = 1;
$conf['tpl']['bootstrap3']['showPageTools'] = 'never';
$conf['tpl']['bootstrap3']['showBadges'] = 0;
$conf['tpl']['bootstrap3']['showWikiInfo'] = 0;
$conf['tpl']['bootstrap3']['useGoogleAnalytics'] = 1;
$conf['tpl']['bootstrap3']['googleAnalyticsTrackID'] = 'UA-174184918-1';
$conf['tpl']['bootstrap3']['browserTitle'] = '@TITLE@ • @WIKI@';
$conf['tpl']['bootstrap3']['browserTitleCharSepNS'] = '/';
$conf['tpl']['bootstrap3']['socialShareProviders'] = '';
$conf['tpl']['bootstrap3']['tagsOnTop'] = 0;
